Repository hapijs/joi, pull requests merged in 2018-11, with the labels that each got.

#1641 Fix wrong data in report
  benchmarks/bench.js
Labels: bug

#1642 Additional tests
  benchmarks/bench.js
  benchmarks/package-lock.json
  benchmarks/package.json
  benchmarks/suite.js
Labels: enhancement, maintenance

#1638 fix condition, add tests for safe numbers
  lib/types/number/index.js
  test/types/number.js
Labels: bug

#1645 Support self references. Closes #1569
  API.md
  lib/ref.js
  lib/set.js
  lib/types/alternatives/index.js
  lib/types/any/index.js
  lib/types/array/index.js
  lib/types/date/index.js
  lib/types/number/index.js
  lib/types/string/index.js
  test/types/alternatives.js
Labels: enhancement

#1648 Move object rename to own function
  lib/types/object/index.js
Labels: non-issue

#1647 Add object().oxor(). Closes #1628
  API.md
  lib/language.js
  lib/types/object/index.js
  test/types/object.js
Labels: enhancement

#1654 Bump to lab@18. Fixes #1653.
  lib/errors.js
  lib/types/alternatives/index.js
  lib/types/any/index.js
  lib/types/date/index.js
  package.json
  test/set.js
  test/types/alternatives.js
  test/types/any.js
  test/types/binary.js
  test/types/lazy.js
  test/types/object.js
Labels: dependency, test

#1652 Throw typed ValidationErrors
  API.md
  lib/errors.js
  lib/index.js
  test/index.js
Labels: enhancement

#1659 Add array().assertItem(). Closes #1656
  API.md
  lib/language.js
  lib/types/array/index.js
  test/types/array.js
Labels: enhancement

#1669 Fix typo: non -> none
  API.md
Labels: documentation
