Repository hapijs/joi, pull requests merged in 2019-04, with the labels that each got.

#1777 V14 temp
  API.md
  README.md
  lib/types/string/index.js
  package.json
  test/errors.js
  test/helper.js
  test/index.js
  test/ref.js
  test/set.js
  test/types/alternatives.js
  test/types/any.js
  test/types/array.js
  test/types/binary.js
  test/types/boolean.js
  test/types/date.js
  test/types/function.js
  test/types/lazy.js
  test/types/number.js
  test/types/object.js
  test/types/string.js
  test/types/symbol.js
Labels: non-issue

#1741 Add installation command
  README.md
Labels: documentation

#1704 Resolved issue of maximum call stack exceeded
  lib/types/string/index.js
Labels: bug

#1765 Faster object/array conversion fails
  benchmarks/suite.js
  lib/types/array/index.js
  lib/types/binary/index.js
  lib/types/object/index.js
  test/types/array.js
  test/types/object.js
Labels: enhancement

#1750 Pass options to pattern validation to support refs
  test/types/object.js
Labels: bug
