Repository hapijs/joi, pull requests merged in 2019-05, with the labels that each got.

#1804 Clarify referenced parameter resolution
  API.md
Labels: documentation

#1801 remove strip from defaults now that it has been removed
  lib/types/any/index.js
Labels: bug

#1819 Reduce reach
  lib/errors.js
  lib/language.js
Labels: enhancement

#1723 Allow validate options to be passed through assert/attempt #1722
  API.md
  lib/index.js
  test/index.js
Labels: enhancement
