Repository hapijs/joi, pull requests merged in 2021-12, with the labels that each got.

#2589 merge subschema matches when subchemas are objects, or alternatives of objects
  lib/types/alternatives.js
  test/types/alternatives.js
Labels: bug

#2649 fix: Joi.string().hostname() not returning errors for CIDR notation
  lib/types/string.js
  test/types/string.js
Labels: bug

#2651 Fix label elimination for externals
  lib/validator.js
  test/validator.js
Labels: bug

#2665 Fix typings on any.external(): add helpers argument
  lib/index.d.ts
Labels: bug, types

#2698 Add Date -> Joi.DateSchema map to ObjectPropertiesSchema<T>
  lib/index.d.ts
Labels: types

#2703 issue #2606: pass TSchema from ObjectSchema to .validate function
  lib/index.d.ts
Labels: types

#2666 Updated `multiple` rule to support decimal/float base
  lib/types/number.js
Labels: bug
