Repository hapijs/joi, pull requests merged in 2022-10, with the labels that each got.

#2860 fix: allow all schema types to be defined and inferred
  lib/index.d.ts
  test/index.ts
Labels: types

#2863 fix a typo in bool type description
  lib/index.d.ts
Labels: types

#2859 Fix/throwing errors if required argument is omitted
  lib/base.js
  test/types/number.js
  test/types/string.js
Labels: bug

#2762 Add isPresent option to object dependencies
  API.md
  benchmarks/package.json
  benchmarks/suite.js
  lib/index.d.ts
  lib/types/keys.js
  test/types/object.js
Labels: feature

#2867 fix: better unsafe check of exponential numbers
  benchmarks/suite.js
  lib/types/number.js
  test/types/number.js
Labels: bug
