Repository hapijs/joi, pull requests merged in 2022-09, with the labels that each got.

#2836 fix(d.ts): allow nested object schema for strictly typed object
  lib/index.d.ts
  test/index.ts
Labels: bug, types

#2819 Add artifact to typings.
  lib/index.d.ts
Labels: types

#2797 feat(d.ts): improve attempt return type
  lib/index.d.ts
Labels: types

#2829 fix(d.ts)!: type details param of ValidationError constructor
  lib/index.d.ts
  test/index.ts
Labels: types

#2788 Include local into `ErrorReport` type
  lib/index.d.ts
Labels: types

#2808 feat(d.ts): Add type information for `maxDomainSegments` to `EmailOptions` and `DomainOptions` interfaces
  lib/index.d.ts
Labels: types

#2842 Fix spelling
  API.md
  lib/index.d.ts
  test/base.js
Labels: documentation

#2838 feat: change validateAsync return type to match options
  lib/index.d.ts
  test/index.ts
Labels: types

#2841 Allow sub-objects for TypeScript strict object schema
  lib/index.d.ts
  test/index.ts
Labels: types

#2843 chore: update license
  LICENSE.md
Labels: documentation

#2844 types: support strict alternatives
  lib/index.d.ts
  test/index.ts
Labels: types

#2851 Try improving handling of unions
  lib/index.d.ts
  test/index.ts
Labels: bug, types
