Repository hapijs/joi, pull requests merged in 2023-02, with the labels that each got.

#2908 Fix return spelling in the documentation
  API.md
Labels: documentation

#2909 chore: use latest address module
  API.md
  benchmarks/bench.js
  browser/package.json
  browser/tests/index.js
  browser/webpack.config.js
  lib/annotate.js
  lib/base.js
  lib/cache.js
  lib/common.js
  lib/compile.js
  lib/extend.js
  lib/index.d.ts
  lib/index.js
  lib/manifest.js
  lib/messages.js
  lib/modify.js
  lib/ref.js
  lib/state.js
  lib/template.js
  lib/trace.js
  lib/types/alternatives.js
  lib/types/any.js
  lib/types/array.js
  lib/types/binary.js
  lib/types/boolean.js
  lib/types/date.js
  lib/types/function.js
  lib/types/keys.js
  lib/types/link.js
  lib/types/number.js
  lib/types/string.js
  lib/types/symbol.js
  lib/validator.js
  lib/values.js
  package.json
  test/trace.js
  test/types/string.js
Labels: feature

#2910 fix: transpile optional chaining
  browser/webpack.config.js
Labels: bug

#2916 fix: properly transform domain
  benchmarks/package.json
  browser/tests/index.js
  lib/types/string.js
Labels: bug
