Repository hapijs/joi, pull requests merged in 2024-01, with the labels that each got.

#3013 fix: precision issue on number().multiple()
  .github/workflows/ci-module.yml
  lib/types/number.js
  test/errors.js
  test/types/number.js
Labels: bug

#3009 fix: LanguageMessages type now supports languages in TypeScript
  lib/index.d.ts
Labels: bug, types

#3001 fix: do not override existing labels of underlying schemas in alternatives
  lib/types/alternatives.js
  test/types/alternatives.js
Labels: bug

#2875 Fix for #2874
  API.md
  lib/index.d.ts
Labels: documentation, types

#3014 feat: hex prefix
  API.md
  lib/index.d.ts
  lib/types/string.js
  test/types/string.js
Labels: feature

#3016 fix: domain default tld validation
  lib/types/string.js
  package.json
  test/types/string.js
Labels: bug
